# Generated by Django 3.2.19 on 2023-10-15 16:00

from django.conf import settings
from django.db import migrations, models
import splitwise_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise_app', '0003_userbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('EQUAL', 'Equal'), ('EXACT', 'Exact'), ('PERCENT', 'Percent')], default='EQUAL', max_length=10, validators=[splitwise_app.validators.validate_expense_amount]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='participants',
            field=models.ManyToManyField(related_name='expenses_participated', to=settings.AUTH_USER_MODEL, validators=[splitwise_app.validators.validate_participants_limit]),
        ),
    ]
