# Generated by Django 3.2.19 on 2023-10-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise_app', '0005_remove_customuser_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_number',
        ),
    ]
