# Generated by Django 3.2.19 on 2023-10-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise_app', '0006_remove_customuser_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
